# Generated by Django 2.2 on 2021-06-15 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Summarizer', '0002_save_sum_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='save_sum',
            name='summary',
            field=models.CharField(max_length=2000),
        ),
    ]
